#!/bin/sh

PLATFORM="linux"
ARCH="x64"

NODE_API_VERSION="69"
ELECTRON_VERSION="4.0.8"

scripts/build-node-sass.sh $PLATFORM $ARCH $NODE_API_VERSION $ELECTRON_VERSION

NODE_API_VERSION="73"
ELECTRON_VERSION="6.0.2"

scripts/build-node-sass.sh $PLATFORM $ARCH $NODE_API_VERSION $ELECTRON_VERSION
